### PR TITLE
Added setter for dot notation when working with env vars

### PR DESCRIPTION
**Pull request by klaussilveira**
Mapping environment variables is a huge boost in deployment productivity. But when you're dealing with nested parameters, it's a huge pain to map variables properly, since you have to store a JSON object inside the environment variable. This PR ads a new feature that allows you to use dot notation to reach nested values. 

Example:

```json
"env-map": {
    "database.default.dbname": "DEFAULT_DB_NAME",
}
```

### CODE REVIEW

**Comment by stof** [comment]
There is no nested values in Symfony parameters (they are a flat map). And dots are valid in YAML keys (and they are commonly used in symfony parameter names because of the naming convention). So this is a huge BC break.

**Comment by klaussilveira** [comment]
I assume this library is not Symfony-specific. For example, i'm using it for Silex projects, as well framework-less PHP applications. 

Regarding the BC break: we can use another token for level notation. Maybe `:` or `::`.

**Comment by stof** [comment]
@klaussilveira the issue is that these are also valid in YAML keys.

and indeed, it is not specific to Symfony. But it is used in most Symfony projects (given that it is included by default), so we should avoid doing BC breaks which would break the standard usage in Symfony.

**Comment by klaussilveira** [comment]
Any suggestion to avoid BC breaks in this implementation? Maybe a special env-map key, dedicated to nested mapping?

**Comment by RTodorov** [comment]
:+1:

**Pull request closed without merging**
