### PR TITLE
Add Symfony 5 support

### PR DESCRIPTION
**Pull request by simonberton**
#SymfonyHackday

### CODE REVIEW

**Comment by DonCallisto** [comment]
@simonberton you can take a look at https://github.com/Incenteev/ParameterHandler/pull/129 to see why your tests are failing and fix them.

**Comment by simonberton** [comment]
Hi @DonCallisto Should we remove the php 5.4, 5.5, 5.6 from the travis file ?
Thanks

**Comment by DonCallisto** [comment]
Usually I would say no because this PR is for Symfony5 support so should not take into account php minimum version bumping but, as test will fail, I suggest to remove them in order to make the CI go green.
When the CI is green I suggest to squash all the things in one single commit.

**Comment by DonCallisto** [comment]
Why did you closed this?

**Pull request closed without merging**
